remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: 6530250441
description: 👉 My name is Pasin Harnkham Love You So Much❤️❤️.
show_downloads: true
google_analytics:
theme: jekyll-theme-architect
