remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Pasin Harnkham
description: description: Tactile is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-tactile
